theme = "PaperMod"

baseURL = "http://localhost/"
languageCode = "en-us"
title = "Vishal's Website"
theme = "PaperMod"

[params]
  homeInfoParams = { Title = "Welcome to my personal site 🚀", Content = "This is my portfolio website made with Hugo + PaperMod Hello." }
12:04 AM 6/09/2025